//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResWebsite.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IESupply
    {
        public int TransID { get; set; }
        public Nullable<int> SupplyID { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<int> Supplier { get; set; }
        public string TypeName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Item Item { get; set; }
        public virtual Supplier Supplier1 { get; set; }
    }
}
